import initScrollSuave from './modules/scroll-suave.js';
import InitAnimacaoScroll from './modules/animacao-scroll.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown_menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initDateObject from './modules/date-object.js';
import initFetchAnimais from './modules/fetch-animais.js';

initScrollSuave();
InitAnimacaoScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initDateObject();
initFetchAnimais();